/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checklist` | `/checklist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/currency` | `/currency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/emergency` | `/emergency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/nearby` | `/nearby`; params?: Router.UnknownInputParams; } | { pathname: `/guide/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/checklist` | `/checklist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/currency` | `/currency`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/emergency` | `/emergency`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/nearby` | `/nearby`; params?: Router.UnknownOutputParams; } | { pathname: `/guide/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/checklist${`?${string}` | `#${string}` | ''}` | `/checklist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/currency${`?${string}` | `#${string}` | ''}` | `/currency${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/emergency${`?${string}` | `#${string}` | ''}` | `/emergency${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/nearby${`?${string}` | `#${string}` | ''}` | `/nearby${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checklist` | `/checklist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/currency` | `/currency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/emergency` | `/emergency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/nearby` | `/nearby`; params?: Router.UnknownInputParams; } | `/guide/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/guide/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
